apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: setting-puuid-info-cron-workflow
  namespace: lol-duo
spec:
  concurrencyPolicy: "Replace"
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: setting-user-puuid-info
              template: cron-job-template
              arguments:
                  parameters: [{name: command, value: prodSetPuuId_SQS_INPUT}]
            - name: call-riot-api-get-puuid
              dependencies: [setting-user-puuid-info]
              template: cron-job-template
              arguments:
                  parameters: [{name: command, value: prodSetPuuId_CallApi}]
              withItems: [1,2,3]
      - name: cron-job-template
        inputs:
          parameters:
            - name: command
        container:
          image: public.ecr.aws/x6k4k7p6/lol-duo:CronJob
          imagePullPolicy: "Always"
          command: [npm, run, "{{inputs.parameters.command}}"]
          env:
            - name: SQS_NAME
              value: Riot_API_SQS.fifo
            - name: PUUID_SQS_NAME
              value: puuidSQS.fifo
            - name: Slack_Channel
              value: cron-job
            - name: RIOT_SERVICE_URL
              value: http://prod-riot-api-service
            - name: Slack_Bot_Token
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: Slack_Bot_Token
            - name: CONST_AWS_SQS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: CONST_AWS_SQS_ACCESS_KEY_ID
            - name: CONST_AWS_SQS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: CONST_AWS_SQS_SECRET_ACCESS_KEY
            - name: mongoDB_URI
              value: mongodb://10.0.0.57:27017/?directConnection=true&serverSelectionTimeoutMS=2000