# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: front-bf0285b7c1d6e5c5aa7a20908b7bbc8d932c1bfe
  pullPolicy: Always

deployment:
  name: prod-lol-duo-front-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-lol-duo-front-service
  namespace: lol-duo
  type: NodePort
  nodePort: 30001
  httpPort: 80
  targetPort: 80