# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: front-97b026934c7693090f608669b78ac9eafff56485
  pullPolicy: Always

deployment:
  name: prod-lol-duo-front-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-lol-duo-front-service
  namespace: lol-duo
  type: NodePort
  nodePort: 30000
  httpPort: 80
  targetPort: 3000