# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: front-885b64c7ff30bc76a63cbefda4474af26ae30d58
  pullPolicy: Always

deployment:
  name: prod-lol-duo-front-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-lol-duo-front-service
  namespace: lol-duo
  type: NodePort
  nodePort: 30001
  httpPort: 80
  targetPort: 80