# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: 79ab4b7f8ca5a19fba00eb1804f8690da35dfd72
  pullPolicy: Always

deployment:
  name: prod-backend-server-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-backend-server-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 3000