# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: d87be48a4c5a8777786fdb99840547f99e96174d
  pullPolicy: Always

deployment:
  name: prod-backend-server-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-backend-server-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 3000