# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: 0261c0db16c847577f366c2ebf7f2d3f9763f3f5
  pullPolicy: Always

deployment:
  name: prod-backend-server-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-backend-server-service
  namespace: lol-duo
  type: NodePort
  nodePort: 30002
  httpPort: 80
  targetPort: 3000