# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: 9ac7df81a7a15cc9825e6f792323e16fda60fb8f
  pullPolicy: Always

deployment:
  name: prod-backend-server-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-backend-server-service
  namespace: lol-duo
  type: NodePort
  nodePort: 30002
  httpPort: 80
  targetPort: 3000