apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-monitoring-prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /prometheus
    server: fs-0b6cc3434ae773657.efs.ap-northeast-2.amazonaws.com