apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: lol-duo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-09cc9de5218fac859.efs.ap-northeast-2.amazonaws.com