# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: cb99bbd2278310efce254c8865425d492143eba3
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80