# values.yaml
image:
  repository: 431955170593.dkr.ecr.ap-northeast-2.amazonaws.com/lol-duo
  tag: 234934ec32511ce48c399e7eb4acdcaae72e18bc
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80