# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: c8cd97b64e021f1bf3db6732d902c4046064b0ac
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80