# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo
  tag: 1361a9ac4c015dcb5eaa13c627caf15ae2099c72
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80