# values.yaml
image:
  repository: public.ecr.aws/x6k4k7p6/lol-duo-images
  tag: 4e15aa38787a254e0847de2201050810a1845134
  pullPolicy: Always

deployment:
  name: prod-lol-duo-front-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-lol-duo-front-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 3000