# values.yaml
image:
  repository: 431955170593.dkr.ecr.ap-northeast-2.amazonaws.com/lol-duo
  tag: 54d035be434902bc631e60bd6493c5f2c185d769
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80