# values.yaml
image:
  repository: 431955170593.dkr.ecr.ap-northeast-2.amazonaws.com/lol-duo
  tag: ca45672b200c01f25db35c45cd89677e919fc700
  pullPolicy: Always

deployment:
  name: prod-riot-api-deployment
  namespace: lol-duo
  replicas: 1

service:
  name: prod-riot-api-service
  namespace: lol-duo
  type: ClusterIP
  httpPort: 80
  targetPort: 80