apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: get-server-info-cron-job
  namespace: lol-duo
spec:
  schedule: "00 * * * *" # 00 * * * * UTC every hour
  concurrencyPolicy: "Replace"
  workflowSpec:
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: get-server-info
              template: cron-job-template
              arguments:
                parameters: [{name: command, value: prodGetServerInfo}]
      - name: cron-job-template
        inputs:
          parameters:
            - name: command
        container:
          image: 431955170593.dkr.ecr.ap-northeast-2.amazonaws.com/lol-duo:CronJob
          imagePullPolicy: "Always"
          command: [npm, run, "{{inputs.parameters.command}}"]
          env:
            - name: TIME_PER_SECOND
              value: "3600"
            - name: Slack_Channel
              value: cron-job
            - name: RIOT_SERVICE_URL
              value: http://prod-riot-api-service
            - name: Slack_Bot_Token
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: Slack_Bot_Token