apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: setting-only-match-info-cron-workflow
  namespace: lol-duo
spec:
  schedule: "00 00 1 1 1" # 00:00 UTC every Monday
  concurrencyPolicy: "Replace"
  workflowSpec:
    arguments:
      parameters:
        - name: MATCH_COUNT
          value: "1000"
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: call-riot-api
              template: cron-job-template
              arguments:
                parameters: [{name: command, value: prodSetMatchId_CallApi}]
              withItems: [1,2]
      - name: cron-job-template
        inputs:
          parameters:
            - name: command
        container:
          image: public.ecr.aws/x6k4k7p6/lol-duo:CronJob
          imagePullPolicy: "Always"
          command: [npm, run, "{{inputs.parameters.command}}"]
          env:
            - name: MATCH_SQS_NAME
              value: matchSQS.fifo
            - name: MATCH_COUNT
              value: "{{workflow.parameters.MATCH_COUNT}}"
            - name: Slack_Channel
              value: cron-job
            - name: RIOT_SERVICE_URL
              value: http://prod-riot-api-service
            - name: Slack_Bot_Token
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: Slack_Bot_Token
            - name: CONST_AWS_SQS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: CONST_AWS_SQS_ACCESS_KEY_ID
            - name: CONST_AWS_SQS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: lol-duo-api-secret
                  key: CONST_AWS_SQS_SECRET_ACCESS_KEY
            - name: mongoDB_URI
              value: mongodb://10.0.0.57:27017